namespace raytracer
{
    /// <summary>
    ///     A ray is generated by the camera from a sample.
    ///     It is then launched in the scene, from where it gets a spectrum
    ///     <seealso cref="Camera" />
    ///     <seealso cref="Sample" />
    ///     <seealso cref="Scene" />
    ///     <seealso cref="Spectrum" />
    /// </summary>
    internal class Ray
    {
        /// <summary>
        ///     The sample used to generate the ray
        /// </summary>
        private Sample Sample;
    }
}