using System.Numerics;

namespace raytracer
{
    /// <summary>
    ///     A ray is generated by the camera from a sample.
    ///     It is then launched in the scene, from where it gets a spectrum
    ///     <seealso cref="Camera" />
    ///     <seealso cref="Sample" />
    ///     <seealso cref="Scene" />
    ///     <seealso cref="Spectrum" />
    /// </summary>
    public class Ray
    {
        /// <summary>
        ///     The sample used to generate the ray
        /// </summary>
        private Sample Sample;

        /// <summary>
        /// Create a ray from a direction an origin, and the sample
        /// used to generate it.
        /// </summary>
        /// <param name="direction"></param>
        /// <param name="origin"></param>
        /// <param name="sample"></param>
        public Ray(Vector3 direction, Vector3 origin, Sample sample)
        {
            Direction = direction;
            Origin = origin;
            Sample = sample;
        }

        /// <summary>
        ///     The direction of the vector.
        ///     This direction is not normalized.
        /// </summary>
        public Vector3 Direction { get; private set; }

        /// <summary>
        ///     The origin point of a ray
        /// </summary>
        public Vector3 Origin { get; private set; }
    }
}